kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: letchik-cluster
networking:
  ipFamily: ipv4
  apiServerAddress: 127.0.0.1

# enable containerd registry config dir (to support local Docker image registry)
containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".registry]
    config_path = "/etc/containerd/certs.d"

# create control plane and 3 worker nodes
nodes:
- role: control-plane
  kubeadmConfigPatches:
    - |
      kind: InitConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    protocol: TCP
- role: worker
- role: worker
- role: worker
